version: '3.0'

services:
  rasa_core:
    image: rasa/rasa_core:stable
    ports:
      - 5005:5005
    volumes:
      - ./models/rasa_core:/app/models
      - ./config:/app/config
    command:
      - start
      - --core
      - models
      - --enable_api
      - --cors
      - "*"
      - -c
      - rest
      - --endpoints
      - config/endpoints.yml
      - -u
      - current
  # rasa_nlu:
  #   image: rasa/rasa_nlu:0.15.0-full
  #   ports:
  #     - 5000:5000
  #   volumes:
  #     - ./models:/app/models
  #   command:
  #     - start
  #     - --path
  #     - models
  action_server:
    image: rasa/rasa_core_sdk:0.12.2
    ports:
      - "0.0.0.0:5055:5055"
    volumes:
      - ./actions:/app/actions
